In [1]:
import torch

In [17]:
x = torch.randint(0, 10, (3, 3))
x

tensor([[6, 6, 9],
        [1, 1, 4],
        [4, 1, 4]])

In [18]:
x

tensor([[6, 6, 9],
        [1, 1, 4],
        [4, 1, 4]])

In [20]:
x.transpose(1,0 )

tensor([[6, 1, 4],
        [6, 1, 1],
        [9, 4, 4]])